import type { PracticeResults } from '@/lib/api';
const time = (seconds:number) => `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
export function FeedbackDetails({results}:{results:PracticeResults}) {
  return <div className="mt-6 space-y-6">
    <section className="rounded-3xl border bg-card p-6"><h2 className="text-xl font-semibold">What to improve</h2>{results.improvements.map((i,n)=><div className="mt-4" key={n}><p className="font-semibold">{i.category}: {i.observation}</p><p>{i.suggestion}</p></div>)}</section>
    <section className="rounded-3xl border bg-card p-6"><h2 className="text-xl font-semibold">Grammar and phrasing</h2>{results.grammar?.length ? results.grammar.map((g,n)=><div className="mt-4" key={n}><p>You said: “{g.original}”</p><p className="font-semibold">Try: “{g.suggested}”</p><p className="text-muted-foreground">{g.explanation}</p></div>) : <p className="mt-3">No supported grammar corrections were returned. This is not a guarantee of error-free speech.</p>}</section>
    <section className="rounded-3xl border bg-card p-6"><h2 className="text-xl font-semibold">Speech delivery</h2><p className="mt-3">{results.measurements.wordsPerMinute} words/min · {results.measurements.fillerCount ?? 0} fillers · {results.measurements.durationSeconds}s spoken / {results.measurements.targetSeconds}s target</p>
      {results.speech?.timestampsAvailable ? <><h3 className="mt-4 font-semibold">Filler locations</h3>{results.speech.fillers.length ? results.speech.fillers.slice(0,30).map((f,n)=><span key={n} className="mr-3 inline-block">{time(f.start)} “{f.text}”</span>) : <p>No clear fillers detected in the transcript.</p>}<h3 className="mt-4 font-semibold">Pauses of 1.5 seconds or longer</h3><p className="text-sm text-muted-foreground">Pauses can be intentional. Review these in context.</p>{results.speech.pauses.length ? results.speech.pauses.slice(0,20).map((p,n)=><p key={n}>{time(p.start)}: {p.durationSeconds}s between “{p.after}” and “{p.before}”</p>) : <p>None detected between transcribed words.</p>}</> : <p className="mt-2 text-muted-foreground">Word timestamps are unavailable for this attempt.</p>}
      <p className="mt-3 text-sm text-muted-foreground">These measurements describe pace, wording and pauses. They do not measure confidence, pronunciation, or actual audience engagement.</p>
    </section>
    <section className="rounded-3xl border bg-card p-6"><h2 className="text-xl font-semibold">Comparison with your document</h2>{results.documentAlignment?.length ? results.documentAlignment.map((d,n)=><div key={n} className="mt-5 border-t pt-4"><p className="font-semibold">Page {d.page} · {d.status}</p><p>Document: “{d.sourceQuote}”</p><p>{d.spokenQuote ? `You said: “${d.spokenQuote}”` : 'No supporting quote found in your speech.'}</p><p className="mt-2">{d.observation}</p><p className="font-medium">{d.suggestion}</p></div>) : <p className="mt-3">{results.documentComparison?.uploadedDocuments ? 'Documents were supplied, but the evaluator returned no verifiable page-linked findings. Retry evaluation; no alignment claim is made.' : 'No supporting document was uploaded for this session.'}</p>}</section>
  </div>;
}
